# Generated by Django 3.1.4 on 2020-12-29 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractsabotage',
            options={'verbose_name': 'sabotage', 'verbose_name_plural': 'sabotages'},
        ),
        migrations.AddField(
            model_name='problem',
            name='index',
            field=models.IntegerField(default=1, help_text='Индекс задачи', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(default='', help_text='Название задачи', max_length=100),
            preserve_default=False,
        ),
    ]
