# Generated by Django 3.1.4 on 2020-12-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20201229_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_data',
            field=models.TextField(default='', help_text='Входные данные'),
            preserve_default=False,
        ),
    ]
