# Generated by Django 3.1.4 on 2020-12-29 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_problem_input_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closesubmissionsabotage',
            name='problem',
            field=models.ForeignKey(blank=True, help_text='Какую задачу закрыть. None, если все', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_submission_sabotages', to='contests.problem'),
        ),
    ]
