# Generated by Django 3.1.4 on 2020-12-29 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20201229_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveTaskSabotage',
            fields=[
                ('abstractsabotage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contests.abstractsabotage')),
                ('statement', models.TextField(help_text='Условие задачи, которую надо решить. Поддерживается HTML')),
                ('correct_answer', models.TextField(help_text='Правильный ответ')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('contests.abstractsabotage',),
        ),
        migrations.AlterField(
            model_name='problem',
            name='statement',
            field=models.TextField(help_text='Условие задачи, поддерживается HTML'),
        ),
    ]
