# Generated by Django 3.1.4 on 2020-12-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20201229_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='max_sabotage_users',
            field=models.IntegerField(default=3, help_text='Максимальное количество участников для саботажа'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problem_score_coefficient',
            field=models.FloatField(default=0.05, help_text='Коэффициент уменьшения стоимости задачи после каждого успешного решения'),
        ),
    ]
