# Generated by Django 3.1.4 on 2020-12-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20201230_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checker',
            field=models.TextField(blank=True, help_text='Чекер. Программа на питоне, содержащая функцию check(output, answer) -> bool'),
        ),
    ]
