# Generated by Django 3.1.4 on 2020-12-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_problem_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='x',
            field=models.IntegerField(default=0, help_text='Координата'),
        ),
        migrations.AddField(
            model_name='problem',
            name='y',
            field=models.IntegerField(default=0, help_text='Координата'),
        ),
    ]
