# Generated by Django 3.1.4 on 2020-12-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20201231_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='correct_regex',
        ),
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(default='', help_text='Правильный ответ'),
            preserve_default=False,
        ),
    ]
