# Generated by Django 3.1.4 on 2020-12-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_auto_20201231_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='SabotageTaskTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(help_text='Условие задачи')),
                ('correct_answer', models.TextField(help_text='Правильный ответ')),
            ],
        ),
    ]
